version: '3.8'

services:
  elk:
    build:
      context: ./elk
      dockerfile: Dockerfile
    container_name: elk
    networks:
      elk-net:
        ipv4_address: 172.20.0.10
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  nginx-filebeat:
    build:
      context: ./nginx-filebeat
      dockerfile: Dockerfile
    container_name: nginx-filebeat
    networks:
      - elk-net
    ports:
      - "80:80"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - elk-net

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.11.1
    container_name: metricbeat
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk-net
    depends_on:
      - nginx-filebeat
      - mysql
      - elk
   
networks:
  elk-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
