version: '3.8'

services:
  elk:
    build:
      context: ./elk
      dockerfile: Dockerfile
    container_name: elk
    networks:
      elk-net:
        ipv4_address: 172.20.0.10
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  nginx-filebeat:
    build:
      context: ./nginx-filebeat
      dockerfile: Dockerfile
    container_name: nginx-filebeat
    networks:
      - elk-net
    ports:
      - "80:80"

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      # Para el servicio MySQL, puedes establecer la variable MYSQL_ROOT_HOST a % 
      # para permitir conexiones desde cualquier host
      MYSQL_ROOT_HOST: '%'
    networks:
      - elk-net
    ports:
      - "3306:3306"

  metricbeat:
    build:
      context: ./metricbeat
      dockerfile: Dockerfile
    container_name: metricbeat
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk-net
    depends_on:
      - nginx-filebeat
      - mysql
      - elk

  packetbeat:
    build:
      context: ./packetbeat
      dockerfile: Dockerfile
    container_name: packetbeat
    networks:
      - elk-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_RAW
      - NET_ADMIN
    depends_on:
      - nginx-filebeat
      - mysql
      - elk
   
networks:
  elk-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
