version: '3.8'

services:
  elk:
    build:
      context: ./elk
      dockerfile: Dockerfile
    container_name: elk
    networks:
      elk-net:
        ipv4_address: 172.20.0.10
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  nginx-filebeat:
    build:
      context: ./nginx-filebeat
      dockerfile: Dockerfile
    container_name: nginx-filebeat
    networks:
      - elk-net
    ports:
      - "80:80"
   
networks:
  elk-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
