version: '3.8'

services:
  elk:
    image: sebp/elk:7.16.3
    container_name: elk
    networks:
      elk-net:
        ipv4_address: 172.20.0.10
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

networks:
  elk-net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
